#!/usr/bin/env php
<?php

/* @var $application Sloths\Application\Application */
$application = require getcwd() . '/src/application.php';

$console = new \Sloths\Application\Console\Application($application);
$console->run();